=== Infinite-graph/mod-calendar/ramls/schemas/Opening.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Opening",
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "servicePointId": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "startDate": {
      "type": "string",
      "format": "date-time"
    },
    "endDate": {
      "type": "string",
      "format": "date-time"
    },
    "openingDays": {
      "type": "array",
      "items": {
        "type": "object",
        "$ref": "OpeningDayIncludeWeekdays.json"
      }
    },
    "creationDate": {
      "type": "string",
      "format": "date-time"
    },
    "createdBy": {
      "type": "string"
    }
  },
  "additionalProperties": false,
  "required": [
    "startDate"
  ]
}

=== Infinite-graph/mod-calendar/src/main/resources/init.db_scripts/exception_4.json
{
  "id": "na9927e8-5f79-498e-94ea-8b5b474795c8",
  "servicePointId": "1",
  "name": "exceptional_4",
  "startDate": "2019-01-22",
  "endDate": "2019-01-22",
  "openingDays": [{
    "openingDay": {
      "openingHour": [
        {
          "startTime": "12:00",
          "endTime": "13:00"
        }
      ],
      "allDay": false,
      "open": true
    }
  }]
}

=== Infinite-graph/mod-calendar/src/main/resources/init.db_scripts/opening_4.json
{
  "id": "ha9927e8-5f79-498e-94ea-8b5b474795c8",
  "servicePointId": "1",
  "name": "opening_4",
  "startDate": "2019-01-21",
  "endDate": "2019-02-30",
  "openingDays": [{
    "weekdays": {
      "day": "MONDAY"
    },
    "openingDay": {
      "openingHour": [
        {
          "startTime": "10:00",
          "endTime": "12:00"
        },{
          "startTime": "14:00",
          "endTime": "17:00"
        }
      ],
      "allDay": false,
      "open": true
    }
  }]
}

=== Infinite-graph/mod-calendar/src/main/resources/init.db_scripts/opening_3.json
{
  "id": "ga9927e8-5f79-498e-94ea-8b5b474795c8",
  "servicePointId": "1",
  "name": "opening_3",
  "startDate": "2018-12-11",
  "endDate": "2018-12-22",
  "openingDays": [{
    "weekdays": {
      "day": "FRIDAY"
    },
    "openingDay": {
      "openingHour": [],
      "allDay": true,
      "open": true
    }
  }]
}

=== Infinite-graph/mod-calendar/src/main/resources/init.db_scripts/opening_2.json
{
  "id": "fa9927e8-5f79-498e-94ea-8b5b474795c8",
  "servicePointId": "1",
  "name": "opening_2",
  "startDate": "2018-10-21",
  "endDate": "2018-11-30",
  "openingDays": [{
    "weekdays": {
      "day": "WEDNESDAY"
    },
    "openingDay": {
      "openingHour": [
        {
          "startTime": "10:00",
          "endTime": "12:00"
        }
      ],
      "allDay": false,
      "open": true
    }
  }]
}

=== Infinite-graph/mod-calendar/ramls/examples/opening_get.json
{
  "id": "fa9927e8-5f79-498e-94ea-8b5b474795c8",
  "servicePointId": "1",
  "name": "test3",
  "startDate": "2018-06-01T00:00:00.000+0000",
  "endDate": "2018-08-01T00:00:00.000+0000",
  "openingDays": [
    {
      "weekdays": {
        "day": "MONDAY"
      },
      "openingDay": {
        "openingHour": [
          {
            "startTime": "05:00",
            "endTime": "11:00"
          },
          {
            "startTime": "14:00",
            "endTime": "18:00"
          }
        ],
        "allDay": false,
        "open": true
      }
    }
  ]
}
